FROM golang:1.17-alpine

RUN apk add git make gcc libc-dev

RUN git clone https://github.com/StanMarek/devops-golang-microservice.git /source
RUN pwd & ls -la
WORKDIR /source

RUN go mod tidy

WORKDIR /

CMD ["cp", "-r", "/source", "../volumein/"]